#!/data/data/com.termux/files/usr/bin/bash

shopt -s extglob

function install_packages {
	local packages=( 'binutils' 'coreutils' 'curl' 'dirmngr' 'file' 'gdb' 'git' 'gnupg' 'grep' 'jq' 'make' 'p7zip' 'patch' 'rclone' 'rsync' 'sed' 'silversearcher-ag' 'strace' 'tar' 'termux-api' 'termux-exec' 'tree' 'util-linux' 'unstable-repo' 'unzip' 'vim' 'wget' 'x11-repo' 'xz-utils' 'yasm' 'zip' )
	pkg install "${packages[@]}"
	pkg install qemu-system-x86_64
	
}

function setup_gpgkeys {
	local gpg_keys=( 'github.asc' )
	for gpgk in "${gpg_keys[@]}"; do \
		gpg --import `pwd`/keys/$gpgk; \
	done
	unset gpgk gpg_keys
}

function setup_confs {
	[[ ! -d ~/infection ]] && \
		mkdir -p ~/infection/tests/c
	cp `pwd`/.gitconfig ~/.gitconfig
	
	local FILES=(.bashrc .functions .variables profile)
	for file in "${FILE[@]}"; do
		[[ file = *profile* ]] && {
			cp `pwd`/shells/bash/$file $PREFIX/etc/
			continue;
		}
		cp `pwd`/shells/bash/$file ~/
        done
	unset FILES file

	cp -r `pwd`/.termux/ ~/
	[[ -e $PREFIX/etc/motd ]] && \
		rm $PREFIX/etc/motd
	setup_gpgkeys
}

install_packages
setup_confs
