#!/data/data/com.termux/files/usr/bin/bash

shopt -s extglob

function install_packages {
	local packages=( 'binutils' 'coreutils' 'curl' 'dirmngr' 'file' 'git' 'gnupg' 'grep' 'jq' 'make' 'p7zip' 'patch' 'rclone' 'rsync' 'silversearcher-ag' 'strace' 'tar' 'termux-exec' 'tree' 'util-linux' 'unstable-repo' 'unzip' 'wget' 'x11-repo' 'xz-utils' 'yasm' 'zip' )
	pkg install "${packages[@]}"
	pkg install qemu-system-x86_64
	
}

function setup_gpgkeys {
	gpg_keys=( 'github.asc' )
	for gpgk in "${gpg_keys[@]}"; do \
		gpg --import `pwd`/keys/$gpgk; \
	done
}

function setup_confs {
	[[ ! -d ~/infection ]] && \
		mkdir -p ~/infection/tests/c
	cp `pwd`/.gitconfig ~/.gitconfig
	cp `pwd`/shells/bash/@(.|)[a-zA-Z]* ~/
	cp -r `pwd`/.termux/ ~/
	[[ -e $PREFIX/etc/motd ]] && \
		rm $PREFIX/etc/motd
	setup_gpgkeys
}

install_packages
setup_confs
